# ${projectName}

Generated by ArchiGen — Spring Boot project scaffold.

## Structure

```
src/
└── main/java/${packagePath}/
    ├── model/          # JPA entities
    ├── dto/            # Request and response DTOs
    ├── mapper/         # Entity <-> DTO mappers
    ├── repository/     # Spring Data JPA repositories
    ├── service/        # Service interfaces
    │   └── impl/       # Service implementations
    └── controller/     # REST controllers
```

## Getting Started

```bash
./mvnw spring-boot:run
```
